### PR TITLE
Add missing workflow_transition_unsaved_data string

### LINKED ISSUE #623: String workflow_transition_unsaved_data not defined
[`workflow_transition_unsaved_data` is used](https://github.com/pimcore/admin-ui-classic-bundle/blob/7999ef435d84f133d469539b5664c6b1d65c176e/public/js/pimcore/elementservice.js#L1056), but no translations are provided. It looks like the values was not cherry picked over in commit a6615242b156d725b8db09f3cb33720a8e885355.

### PR DESCRIPTION
**Pull request by cancan101**
Closes #623

### CODE REVIEW

**Comment by cancan101** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fashxp** [comment]
could you please rebase to 1.5

**Comment by cancan101** [comment]
Do you also want me to change the base branch?

**Comment by fashxp** [comment]
yes please :-)

**Pull request merged**
