### PR TITLE
Respect the user's timezone in the version preview and in CSV exports

### PR DESCRIPTION
**Pull request by markus-moser**
Part of https://github.com/pimcore/pimcore/issues/16184.

Depends on https://github.com/pimcore/pimcore/pull/17117

### CODE REVIEW

**Comment by markus-moser** [comment]
Tests will work as soon as https://github.com/pimcore/pimcore/pull/17117 gets released.

**Comment by markus-moser** [comment]
We need to wait with the merge for the next minor release of the core otherwise tests will fail.

**Comment by blankse** [comment]
@markus-moser You need to bump the Pimcore Version in the composer.json when this is a requirement

**Comment by markus-moser** [comment]
@blankse Yes, we will need to do this anyways during the release - we have some other PR pairs like that.

**Pull request merged**
