### PR TITLE
Added support for import/export quantity value unit definition 

### PR DESCRIPTION
**Pull request by prunepal333**
Separates the UI changes from this PR:
pimcore/pimcore/pull/13401: Add Import/Export Quantity value unit definitions support #14136
from pimcore/pimcore repository.

### CODE REVIEW

**Comment by robertSt7** [comment]
@prunepal333 Thanks a lot for creating this PR. Could you also please sign the CLA? Thanks

**Comment by prunepal333** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by prunepal333** [comment]
recheck

**Comment by robertSt7** [comment]
@prunepal333 Please merge 1.x again in your branch to fix the checks. Thanks

**Comment by robertSt7** [comment]
@prunepal333 Thank you for your contribution

**Pull request merged**
