### PR TITLE
[Bugfix] textLayoutPreviewAction does not assign a name to the text element

### PR DESCRIPTION
**Pull request by dark-cms**
To be able to use the preview in the class editor, an object with a name is expected. 
The solution provided is only used for the preview and has no effect on other areas.

Currently, the preview options in the demo systems of Pimcore do not seem to work and throw an error 500

### CODE REVIEW

**Comment by dark-cms** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dark-cms** [comment]
recheck

**Comment by robertSt7** [comment]
@dark-cms Since this is a bugfix, could you please rebase the PR to 1.3? Thanks

**Comment by robertSt7** [comment]
Hi @dark-cms Could you please change the base branch to 1.4? Thanks

**Comment by robertSt7** [comment]
closed in favor of https://github.com/pimcore/admin-ui-classic-bundle/pull/518

**Pull request closed without merging**
