### PR TITLE
[Thumbnail] Mirror image via thumbnail configuration

### PR DESCRIPTION
**Pull request by youwe-petervanderwal**
Technically everything was prepared already in Pimcore since https://github.com/pimcore/pimcore/commit/6c47f7f9b34e779981815030e20f26f33dc300af#diff-6e26e398c3b9ab26394bfc4f6ef484880c9c1bd00d9b650ebd428dfa263e26f6

However, it seems that it never made it to the admin configuration.

Better late than never :)

### CODE REVIEW

**Comment by robertSt7** [comment]
@youwe-petervanderwal All works well. One small thing, could you please replace `var` with `const` and `let`? Thanks :)

**Comment by youwe-petervanderwal** [comment]
> @youwe-petervanderwal All works well. One small thing, could you please replace `var` with `const` and `let`? Thanks :)

@robertSt7 Sure, I copied it from the other definitions, do you like me to fix the complete file or only this new part?

**Comment by robertSt7** [comment]
@youwe-petervanderwal Thanks for the fast response. Only the new part please :)

**Comment by robertSt7** [comment]
@youwe-petervanderwal Thanks a lot. 
One more thing. It seems that you translated the values for nl.
We handle this kind of stuff a little bit different. We actually only update the English translations keys.
The keys are then synced to PO Editor. https://poeditor.com/join/project/XliCYYgILb
You can then translate it there to different languages.

We export those languages on a regular basis to all bundles.

The default fallback is english anyways.
Could you please remove all updates from the non-english files?

Thank you!

**Comment by robertSt7** [comment]
@youwe-petervanderwal Thanks a lot for your contribution :)

**Pull request merged**
