### PR TITLE
Add translations for missing keys in classification store.

### PR DESCRIPTION
**Pull request by sid-mdt**
See https://github.com/pimcore/pimcore/issues/16646

Translation added for field types in classification store to show user friendly names.

### CODE REVIEW

**Comment by sid-mdt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sid-mdt** [comment]
hi @wisconaut, on this PR, one of the checks is failing which is related to CLA assistant. 
Any idea what I need to do here.

**Comment by ghost** [comment]
@sid-mdt Hi, we re-triggered the check and not it fits. Thanks, we'll take care.

**Comment by sid-mdt** [comment]
Ok, thanks

**Review by mattamon — CHANGES_REQUESTED** [review]
Hey @sid-mdt thank you for your contribution.

I just checked your PR and it seems that you changed it for all languages. 
We handle this kind of stuff a little bit different. We actually only update the English translations keys.
The keys are then synced to PO Editor. https://poeditor.com/join/project/XliCYYgILb
You can then translate it there to different languages.

We export those languages on a regular basis to all bundles. 

The default fallback is english anyways. 
Could you please remove all updates from the non-english files?

Thank you!

**Comment by sid-mdt** [comment]
hi @mattamon,
I have removed the newly added translation keys from non english files. Please have a look.

**Review by mattamon — APPROVED** [review]
@sid-mdt Thank you very much LGTM!

**Pull request merged**
