### PR TITLE
[Bug] Fix layout issue for not_editable structuredTable

### LINKED ISSUE #90: [Bug] Structured Table columns config ignored when not editable
See https://github.com/pimcore/pimcore/pull/15078

### PR DESCRIPTION
**Pull request by mattamon**
Follow up https://github.com/pimcore/pimcore/pull/15078

### CODE REVIEW

**Comment by mattamon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattamon** [comment]
@APochmann could you please sign the CLA? :)

**Comment by APochmann** [comment]
@mattamon , if you refer to the CLA for pimcore/pimcore (https://cla-assistant.io/pimcore/pimcore), I did that already earlier but ran it again. I could not find specific CLA for pimcore/admin-ui-classic-bundle. If I missed something, could you point me to the right direction?

**Comment by mattamon** [comment]
> I have read the CLA Document and I hereby sign the CLA

You need to sign the CLA for every repository :)

In this case it is sufficient if you comment `I have read the CLA Document and I hereby sign the CLA` here.

**Comment by APochmann** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattamon** [comment]
> I have read the CLA Document and I hereby sign the CLA

Awesome thank you for your quick reaction!!!!

**Pull request merged**
