### PR TITLE
fix wysiwyg editor init var

### LINKED ISSUE #334: [Bug]: Wysiwyg tinyMCE: HTML markup not being saved
### Pimcore version

11

### Steps to reproduce

I encountered a problem in Pimcore 11 concerning the tinyMCE editor. When saving data, it seems the system stores the content without the HTML markup. This behavior is triggered by the keyup event.

Steps to Reproduce:

1. Navigate to the demo at https://demo.pimcore.com/admin/
2. Open any object with a WYSIWYG field, e.g., "Event".
3. Click on the WYSIWYG field and move the cursor either left or right.
4. Autosave will get triggered, sending the data without HTML markup.
5. Refresh the page.
6. The object wysiwyg field doesn't have HTML formatting.

### Actual Behavior

System didn't save the data in HTML format but in pure plain text

### Expected Behavior

The object should save data with HTML format.

### PR DESCRIPTION
**Pull request by piotrecky**
fixed https://github.com/pimcore/admin-ui-classic-bundle/issues/334

### CODE REVIEW

**Comment by piotrecky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by piotrecky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by piotrecky** [comment]
@brusch how can I sign CLA?

**Comment by blankse** [comment]
The email of your commit is not the same email as your github account.

**Pull request closed without merging**
