### PR TITLE
Revert "Fix formatting for alias on relations (#745)"

### LINKED ISSUE #780: Grid Operator | Relation Resolver broken
This is a regression of: https://github.com/pimcore/admin-ui-classic-bundle/pull/745/files (https://github.com/pimcore/admin-ui-classic-bundle/pull/745)

Using Operators like 
- Operator ObjectFIeld Getter
- Operator Any Getter

...won't work anymore and always return the `fullPath` of the given element.

Version: 1.6

### PR DESCRIPTION
**Pull request by cancan101**
This reverts commit 91d1903a946931d9899b4c81fccfd96061fdd46f.

Closes #780

The original fix was at the wrong location in the evaluation tree. Whatever is calling Alias handles result from alias differently from result from DefaultValue. I need to track that down.

Basically without alias, `getFullPath` (or similar) gets called and with alias it does not. Not sure why.

@fashxp 
@solverat
@la-lisa

### CODE REVIEW

**Comment by solverat** [comment]
Yes, that fixes the issue. The original issue (#744) should be addressed at the operator "Alias" itself.

**Comment by cancan101** [comment]
It might be more complicated than just fixing in the alias operator as the alias operator could itself be nested. I have to investigate that

**Comment by cancan101** [comment]
I believe the rendering code path is very different for the case of an Alias vs direct field: https://github.com/pimcore/admin-ui-classic-bundle/blob/e71ee902ab1274a64d6b80d56af28f1855944dfd/src/Service/GridData/DataObject.php#L74-L220

something in the case of the direct field causes it to render as the full path.

**Comment by robertSt7** [comment]
@cancan101 Thanks for reverting your PR. For further discussions I have re-opened the issue https://github.com/pimcore/admin-ui-classic-bundle/issues/744

**Pull request merged**
