### PR TITLE
Feature/add support for an in filter operator to grid helper

### PR DESCRIPTION
**Pull request by mfedak-notebooksbillger**
### Changes in this pull request

Add support for an 'in' filter operator when filtering numerical fields in the grid.

#### Additional info

At Notebooksbilliger we had a need to filter a column in the grid with multiple values. We have created our own bundle to achieve this but we did have to modify some core code. We are currently changing this core file using a composer patch but would love to see this extra operator check included in future.

Example: https://beta.im.ge/i/in-filter-numeric-columns.FM5r79

(Is related to https://github.com/pimcore/pimcore/pull/15315)

### CODE REVIEW

**Comment by aryaantony92** [comment]
To be merged after `pimcore/pimcore:v1.1.0` is released

**Comment by mfedak-notebooksbillger** [comment]
> To be merged after `pimcore/pimcore:v1.1.0` is released

After pimcore/pimcore:v11.1.0

**Comment by aryaantony92** [comment]
@mfedak-notebooksbillger Looks Good. But could you please refactor the code in override.js such that we don't need to take care of the existing options like gt,lt,eq etc. Like we do for Quantity Value using the inheritance here https://github.com/pimcore/admin-ui-classic-bundle/blob/c4b0b48db3c047f3bc646d6959c84eb2f274171b/public/js/pimcore/object/tags/quantityValue.js#L264

https://github.com/pimcore/admin-ui-classic-bundle/blob/c4b0b48db3c047f3bc646d6959c84eb2f274171b/public/js/pimcore/object/tags/quantityValue.js#L266

**Comment by aryaantony92** [comment]
@mfedak-notebooksbillger Thank you for the PR. We will focus on the refactoring https://github.com/pimcore/admin-ui-classic-bundle/pull/115#issuecomment-1723562449 in a follow up PR.

**Pull request merged**
