### PR TITLE
[Bug]: Classificationstore inherited key to watch doens't work

### LINKED ISSUE #138: [Bug]: Classificationstore inherited key to watch doens't work
### Expected behavior

Keys are watched

### Actual behavior

https://github.com/pimcore/pimcore/blob/631a52073541777720403653f987bd62f1ac881f/bundles/AdminBundle/public/js/pimcore/object/tags/classificationstore.js#L74
is never true

### Steps to reproduce

- Create an class with a CS
- Create an object with this class
- Create a child of this object

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #138

### CODE REVIEW

**Comment by robertSt7** [comment]
@eraush Could you please test the inheritance for Localized Fields and Classification Store? Thanks

**Comment by eraush** [comment]
@robertSt7 please have a look at this scenario: 

https://github.com/pimcore/admin-ui-classic-bundle/assets/131660776/536108dd-c1fe-4ed7-ad1d-dd3377c0716b

**Review by dvesh3 — APPROVED** [review]
Looks good. Basically we are cleaning up the dead code.

**Comment by dvesh3** [comment]
> @robertSt7 please have a look at this scenario:
> 
>  fields.are.gone.after.saving.for.child.mp4

@eraush this is not related to the changes done here so please create a separate bug issue. thanks!

**Pull request merged**
