### PR TITLE
Fixed an issue of save, publish and unpublish object when it is not allowed

### PR DESCRIPTION
**Pull request by rahul-pim-dev**
See: https://github.com/pimcore/pimcore/issues/15153

### CODE REVIEW

**Comment by rahul-pim-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rahul-pim-dev** [comment]
recheck

**Comment by blankse** [comment]
Target branch of bug fixes should be `1.4`

**Comment by fashxp** [comment]
this actually doesn't resolve https://github.com/pimcore/pimcore/issues/15153

and I don't think we should merge that change, as it just silently drops save commands and users don't get any feedback anymore that elements are not saved.

**Comment by fashxp** [comment]
Since there is no further feedback, I'll close this for now. 
Feel free to continue the discussion or create a new PR if there are new findings or aspects. 

Thank you very much.

**Pull request closed without merging**
