### PR TITLE
Fix Base Units in QuantityValue Unit Definition GridView

### PR DESCRIPTION
**Pull request by hbauer**
I have created 196 QuantityUnits by api and the value in the column 'Base Unit' column is incorrect. Additionally, the dropdown menu for selecting a Base Unit will only display 25 items.

This issue arises from the restriction of 25 items in the function _unitProxyGetAction_ in the _QuantityValueController_. Although this restriction doesn't affect the paging of the grid view, it limits the _baseUnitStore_ used in _unitsettings.js_ to always contain only the first 25 QuantityUnits. As a result, the Base Units may not be found in some cases and will be displayed as _(Empty)_.

You can see this in the attached screenshots below.

Current Behaviour:
Pimcore 11 - QuantityValue Unit Definition - Wrong

Expected Behaviour:
Pimcore 11 - QuantityValue Unit Definition - Ok

Testfile for Import:
[quantityvalue_units.sql.zip](https://github.com/pimcore/admin-ui-classic-bundle/files/11972862/quantityvalue_units.sql.zip)

### CODE REVIEW

**Comment by hbauer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blankse** [comment]
@hbauer The email address of the commit must be added to your github account to sign the CLA. 
It seems to be a bug so you should set the target branch to `1.0`.

**Comment by hbauer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dvesh3** [comment]
@hbauer thank you for your contribution 💜  could you please also rebase your branch on 1.0? we have lot of unrelated commits in this PR now.

**Comment by hbauer** [comment]
@dvesh3 Hi, i rebased to 1.0. Please check if it's ok now.

**Comment by dvesh3** [comment]
Hey! It still doesn't look good..
image

maybe you can close this one and create a new PR based on 1.0 branch. thanks!

**Pull request closed without merging**
