### PR TITLE
Fix: ManyToOne relation in combo display mode doesn't respect path formatter

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/admin-ui-classic-bundle/issues/638

### CODE REVIEW

**Comment by robertSt7** [comment]
Hi @blankse when I use the example [formatter](https://github.com/pimcore/pimcore/blob/11.x/doc/05_Objects/01_Object_Classes/05_Class_Settings/50_Path_Formatter.md) and add a News Object to the ManyToOne relation I get the following error. Could you please take a look at this? TIA

``Status: 500 | Internal Server Error
URL: /admin/element/get-nice-path
Method: POST
Message: Warning: Undefined array key "fullpath"
Trace: 
in /var/www/html/src/Website/PathFormatter/TheFormatter.php:29
#0 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Controller/Admin/ElementController.php(915): App\Website\PathFormatter\TheFormatter->formatPath(Array, Object(Pimcore\Model\DataObject\Rel), Array, Array)
#1 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Controller/Admin/ElementController.php(539): Pimcore\Bundle\AdminBundle\Controller\Admin\ElementController->convertResultWithPathFormatter(Object(Pimcore\Model\DataObject\Rel), Array, Array, Array)
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\ElementController->getNicePathAction(Object(Symfony\Component\HttpFoundation\Request))
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#7 /var/www/html/public/index.php(20): require_once('/var/www/html/v...')
#8 {main}``

**Comment by blankse** [comment]
@robertSt7 See https://github.com/pimcore/pimcore/pull/17412 

Did you really use the latest example? The example formatter should use "path" (correct for ManyToOne) and "fullpath" array keys (correct for ManyToMany).

**Comment by robertSt7** [comment]
@blankse Yes I do and I am also don't know why there is no `path` or `fullpath`. 

image

**Comment by blankse** [comment]
@robertSt7 Only in the display mode 'combo,' the array key 'path' was missing. I have added it. Could you please test it again?

**Comment by robertSt7** [comment]
@blankse Thanks a lot for all your contributions

**Pull request merged**
