### PR TITLE
[Improvement]: Allow non-admin users to delete their profile picture

### LINKED ISSUE #15826: [Improvement]: User cannot clear own profile picture
### Improvement description

PR #6330 introduced the possibility to clear profile pictures.

However, this is only possible for admin users or users with permission to "users".
From my point of view, a user should also be able to delete their own profile picture if they are allowed to upload one.

### PR DESCRIPTION
**Pull request by Brainshaker95**
Resolves https://github.com/pimcore/pimcore/issues/15826

Please let me know if there are any issues with this solution. I will gladly add some additional changes.

### CODE REVIEW

**Comment by Brainshaker95** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by Brainshaker95** [comment]
recheck

**Comment by robertSt7** [comment]
@Brainshaker95 Thanks for the improvement

**Comment by robertSt7** [comment]
@Brainshaker95 Thanks for the improvement

**Comment by robertSt7** [comment]
see #308

**Pull request merged**
